apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-minimal-api
  namespace: default
  annotations:
    argocd-image-updater.argoproj.io/image-list: myapp=ghcr.io/yar-zar/minimalapi
    argocd-image-updater.argoproj.io/myapp.update-strategy: latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-minimal-api
  template:
    metadata:
      labels:
        app: test-minimal-api
    spec:
      containers:
      - name: test-minimal-api
        image: ghcr.io/yar-zar/minimalapi:latest
        ports:
        - containerPort: 8080  
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"