apiVersion: v1
kind: Service
metadata:
  name: test-minimal-api-service
spec:
  type: ClusterIP  # သို့မဟုတ် Killercoda / Testing အတွက် လိုအပ်ပါက NodePort သို့မဟုတ် LoadBalancer သို့ ပြောင်းသုံးနိုင်ပါသည်
  selector:
    app: test-minimal-api
  ports:
    - protocol: TCP
      port: 80           # Service ကို ခေါ်မည့် Port
      targetPort: 8080   # Pod ထဲရှိ Container ပြေးနေသည့် Port (Minimal API default 8080)